import type { IMFInstitution } from '../../types';

export const IMF_INSTITUTIONS: IMFInstitution[] = [
  {
    id: 'clcam',
    nom: 'CLCAM',
    type: 'Crédit Mutuel',
    localisation: 'National',
    tauxInteret: '12-18% / an',
    montantMin: 50000,
    montantMax: 5000000,
    dureeMax: '24 mois',
    contact: 'clcam.bj',
  },
  {
    id: 'padme',
    nom: 'PADME',
    type: 'Microfinance',
    localisation: 'Sud-Bénin',
    tauxInteret: '15-24% / an',
    montantMin: 25000,
    montantMax: 2000000,
    dureeMax: '12 mois',
    contact: 'padme.org',
  },
  {
    id: 'finadev',
    nom: 'FINADEV',
    type: 'Microfinance',
    localisation: 'National',
    tauxInteret: '18-22% / an',
    montantMin: 100000,
    montantMax: 10000000,
    dureeMax: '36 mois',
    contact: 'finadev.bj',
  },
  {
    id: 'asf',
    nom: 'ASF',
    type: 'ONG Microfinance',
    localisation: 'Sud-Bénin',
    tauxInteret: '15-20% / an',
    montantMin: 50000,
    montantMax: 3000000,
    dureeMax: '18 mois',
    contact: 'asf.bj',
  },
  {
    id: 'papme',
    nom: 'PAPME',
    type: 'Fonds de garantie',
    localisation: 'National',
    tauxInteret: 'Variable',
    montantMin: 500000,
    montantMax: 20000000,
    dureeMax: '60 mois',
    contact: 'papme.bj',
  },
];
