export const theme = {
  colors: {
    primary: '#0055FF',
    primaryLight: '#E9F0FF',
    primaryDark: '#003BCC',
    primaryContainer: '#D0E1FF',
    onPrimary: '#FFFFFF',
    secondary: '#FF9900',
    secondaryContainer: '#FFF3E0',
    onSecondaryContainer: '#E65100',
    background: '#F9FAFC',
    surface: '#FFFFFF',
    surfaceLow: '#F8FAFC',
    surfaceContainer: '#F1F5F9',
    surfaceContainerHigh: '#E2E8F0',
    surfaceContainerHighest: '#CBD5E1',
    surfaceVariant: '#E2E8F0',
    error: '#EF4444',
    errorLight: '#FEE2E2',
    success: '#10B981',
    successLight: '#D1FAE5',
    warning: '#F59E0B',
    warningLight: '#FEF3C7',
    info: '#3B82F6',
    text: '#0C1A30',
    textSecondary: '#475569',
    textLight: '#94A3B8',
    border: '#E2E8F0',
    divider: '#F1F5F9',
    inverseSurface: '#0F172A',
    tertiary: '#7C3AED',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    xs: 2,
    sm: 4,
    md: 8,
    lg: 8,
    xl: 12,
    xxl: 16,
    full: 999,
  },
  typography: {
    h1: { fontSize: 28, lineHeight: 36, fontWeight: '700' as const },
    h2: { fontSize: 24, lineHeight: 32, fontWeight: '700' as const },
    h3: { fontSize: 20, lineHeight: 28, fontWeight: '700' as const },
    h4: { fontSize: 18, lineHeight: 24, fontWeight: '700' as const },
    body: { fontSize: 16, lineHeight: 24, fontWeight: '400' as const },
    bodySmall: { fontSize: 14, lineHeight: 20, fontWeight: '400' as const },
    caption: { fontSize: 12, lineHeight: 16, fontWeight: '600' as const },
    label: { fontSize: 12, lineHeight: 16, fontWeight: '700' as const, letterSpacing: 0 },
    currency: { fontSize: 22, lineHeight: 28, fontWeight: '700' as const },
  },
} as const;
